# Generated by Django 5.0.6 on 2024-06-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactIndexPage',
            new_name='ContactsIndexPage',
        ),
    ]
