# Generated by Django 5.0.6 on 2024-06-18 09:10

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_contactindexpage_contactsindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsindexpage',
            name='body',
        ),
        migrations.AddField(
            model_name='contactsindexpage',
            name='header_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactsindexpage',
            name='school_locations',
            field=wagtail.fields.StreamField([('school_locations', wagtail.blocks.StructBlock([('school_name', wagtail.blocks.CharBlock(help_text='Name of School', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Campus Image', required=True)), ('phone_number', wagtail.blocks.CharBlock(help_text='Input Phone Number', required=False)), ('email', wagtail.blocks.EmailBlock(help_text='Input School Email', required=False)), ('location', wagtail.blocks.TextBlock(help_text='Address of School', required=True)), ('social_media_url', wagtail.blocks.URLBlock(help='Social Media URL', required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsindexpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
