# Generated by Django 5.0.6 on 2024-06-18 19:03

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contactsindexpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsindexpage',
            name='school_locations',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('locations', wagtail.blocks.StructBlock([('school_name', wagtail.blocks.CharBlock(help_text='Name of School', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Campus Image', required=True)), ('phone_number', wagtail.blocks.CharBlock(help_text='Input Phone Number', required=False)), ('email', wagtail.blocks.EmailBlock(help_text='Input School Email', required=False)), ('location', wagtail.blocks.TextBlock(help_text='Address of School', required=True)), ('social_media_url', wagtail.blocks.URLBlock(help='Social Media URL', required=False)), ('background', wagtail.blocks.ChoiceBlock(choices=[('light', 'white'), ('dark', '#10335b')], help='Select background theme'))]))], blank=True, null=True),
        ),
    ]
