# Generated by Django 5.0.6 on 2024-06-19 07:45

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contactsindexpage_school_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsindexpage',
            name='school_locations',
            field=wagtail.fields.StreamField([('locations', wagtail.blocks.StructBlock([('school_branch', wagtail.blocks.CharBlock(help_text="CitySchool Branch ex: 'Yangon', 'Taunggyi'", required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Campus Image', required=True)), ('image_caption', wagtail.blocks.CharBlock(help_text='Campus Image Caption', required=False)), ('phone_number', wagtail.blocks.CharBlock(help_text='Input Phone Number', required=False)), ('email', wagtail.blocks.EmailBlock(help_text='Input School Email', required=False)), ('location', wagtail.blocks.TextBlock(help_text='Address of School', required=True)), ('social_media_url', wagtail.blocks.URLBlock(help='Social Media URL', required=False)), ('background', wagtail.blocks.ChoiceBlock(choices=[('#ffffff', 'Light'), ('#10335b', 'Dark')], help='Select background theme'))]))], blank=True, null=True),
        ),
    ]
