# Generated by Django 5.0.6 on 2024-06-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contactsindexpage_school_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsindexpage',
            old_name='subtitle',
            new_name='header_subtitle',
        ),
    ]
