# Generated by Django 5.1.6 on 2025-02-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_rename_subtitle_contactsindexpage_header_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsindexpage',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
