# Generated by Django 5.1.6 on 2025-02-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contactsindexpage_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsindexpage',
            name='header_image',
        ),
    ]
