# Generated by Django 5.0.6 on 2024-06-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='header_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='header_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
