# Generated by Django 5.0.6 on 2024-06-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blogindexpage_header_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
