# Generated by Django 5.0.6 on 2024-06-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blogindexpage_header_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='intro',
        ),
    ]
