# Generated by Django 5.0.6 on 2024-07-08 20:59

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_blogindexpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_blog',
            field=wagtail.fields.StreamField([('blog_page', wagtail.blocks.PageChooserBlock(page_type=['blog.BlogPage']))], blank=True),
        ),
    ]
