# Generated by Django 5.0.6 on 2024-07-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogindexpage_featured_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogindexpage',
            old_name='featured_blog',
            new_name='featured_blogs',
        ),
    ]
