# Generated by Django 5.0.6 on 2024-08-08 21:53

import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('base', wagtail.blocks.StreamBlock([('heading_block', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.blocks.RichTextBlock(icon='pilcrow', template='blocks/paragraph_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('block_quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('attribute_name', wagtail.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', icon='media', max_height=400, max_width=800, template='blocks/embed_block.html')), ('button_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Button Title', required=True)), ('button_url', wagtail.blocks.PageChooserBlock(help='Choose Link To Internal Page', required=True))])), ('table_block', wagtail.contrib.table_block.blocks.TableBlock(group='Content', template='blocks/table_block.html')), ('typed_table_block', wagtail.contrib.typed_table_block.blocks.TypedTableBlock([('text', wagtail.blocks.CharBlock()), ('numeric', wagtail.blocks.FloatBlock()), ('rich_text', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], group='Content', template='blocks/typed_table_block.html'))], blank=True, use_json_field=True, verbose_name='body')), ('jumbotron', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(help_text='Jumbotron Heading', required=True)), ('subheading', wagtail.blocks.TextBlock(help_text='Jumbotron Subheading', required=False)), ('background', wagtail.images.blocks.ImageChooserBlock(help_text='Background Image', required=False)), ('button_heading', wagtail.blocks.CharBlock(help_text='Button Text', required=True)), ('button_url', wagtail.blocks.PageChooserBlock(help='Choose Link To Internal Page', required=True))]))]),
        ),
    ]
