# Generated by Django 5.0.6 on 2024-08-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_blogpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagegalleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
