# Generated by Django 5.1.6 on 2025-02-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_blogpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='header_image',
        ),
    ]
