# Generated by Django 5.1.6 on 2025-02-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_blogindexpage_header_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['-date']},
        ),
    ]
