# Generated by Django 5.0.6 on 2024-06-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsIndexPage',
            new_name='AboutUsIndexPage',
        ),
    ]
