# Generated by Django 5.0.6 on 2024-06-29 01:32

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_rename_contactusindexpage_aboutusindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusindexpage',
            name='staff_cards',
            field=wagtail.fields.StreamField([('locations', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', required=True)), ('subtitle', wagtail.blocks.TextBlock(help_text='Section Subtitle', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Card Image', required=True)), ('name', wagtail.blocks.CharBlock(help_text='Input Name', required=True)), ('subtitle', wagtail.blocks.CharBlock(help_text='Card Subtitle', required=True))])))]))], blank=True, null=True),
        ),
    ]
