# Generated by Django 5.0.6 on 2024-06-29 03:32

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_aboutusindexpage_staff_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusindexpage',
            name='staff_cards',
            field=wagtail.fields.StreamField([('cards', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Section Title', required=True)), ('subtitle', wagtail.blocks.TextBlock(help_text='Section Subtitle', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Card Image', required=True)), ('name', wagtail.blocks.CharBlock(help_text='Input Name', required=True)), ('subtitle', wagtail.blocks.CharBlock(help_text='Card Subtitle', required=True))])))])), ('base', wagtail.blocks.StreamBlock([('heading_block', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('paragraph_block', wagtail.blocks.RichTextBlock(icon='pilcrow', template='blocks/paragraph_block.html')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))])), ('block_quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('attribute_name', wagtail.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/watch?v=SGJFWirQ3ks', icon='media', max_height=400, max_width=800, template='blocks/embed_block.html')), ('button_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Button Title', required=True)), ('button_url', wagtail.blocks.PageChooserBlock(help='Choose Link To Internal Page', required=True))]))]))], blank=True, null=True),
        ),
    ]
