# Generated by Django 5.0.6 on 2024-06-30 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_alter_aboutusindexpage_staff_cards'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusindexpage',
            name='founder_description',
            field=models.TextField(blank=True, help_text="Enter founder's description", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutusindexpage',
            name='founder_image',
            field=models.ForeignKey(blank=True, help_text="Founder's image", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutusindexpage',
            name='founder_name',
            field=models.CharField(blank=True, help_text="Enter Founder's Name", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutusindexpage',
            name='founder_section_title',
            field=models.CharField(blank=True, help_text="Enter Founder's Name", max_length=255),
        ),
        migrations.AddField(
            model_name='aboutusindexpage',
            name='founder_title',
            field=models.CharField(blank=True, help_text="Enter founder's title", max_length=255),
        ),
    ]
