# Generated by Django 5.0.6 on 2024-06-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0014_alter_aboutusindexpage_founder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusindexpage',
            name='founder_description',
            field=models.TextField(blank=True, help_text="Enter founder's title", max_length=522),
        ),
    ]
