# Generated by Django 5.0.6 on 2024-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0017_alter_aboutusindexpage_founder_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutusindexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='aboutusindexpage',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutusindexpage',
            name='header_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutusindexpage',
            name='header_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
