# Generated by Django 5.0.6 on 2024-07-13 20:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0018_remove_aboutusindexpage_intro_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusindexpage',
            name='gallery_heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aboutusindexpage',
            name='gallery_subheading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AboutUsGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='aboutus.aboutusindexpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
