# Generated by Django 5.0.6 on 2024-06-14 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_hero_cta_homepage_hero_cta_link_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_text',
            new_name='hero_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta1',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action', max_length=255, verbose_name='Hero CTA 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta1_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero CTA link 1'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta2',
            field=models.CharField(blank=True, help_text='Text to display on Call to Action', max_length=255, verbose_name='Hero CTA 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta2_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero CTA link 2'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheading',
            field=models.CharField(blank=True, help_text='Write sub heading for the site', max_length=255),
        ),
    ]
