# Generated by Django 5.0.6 on 2024-06-19 07:45

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagelogogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageFAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('faqs', wagtail.fields.StreamField([('faqs', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='FAQ Section Title', required=True)), ('subtitle', wagtail.blocks.TextBlock(help_text='FAQ Section Subtitle', required=False)), ('faqs', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.TextBlock(help_text='Input Question', required=True)), ('answer', wagtail.blocks.TextBlock(help_text='Input Question', required=True))])))], help_text='Input Frequently Asked Questions'))])),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
