# Generated by Django 5.0.6 on 2024-06-19 08:42

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepagefaqs_page_alter_homepagefaqs_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='faqs',
            field=wagtail.fields.StreamField([('faqs', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='FAQ Section Title', required=True)), ('subtitle', wagtail.blocks.TextBlock(help_text='FAQ Section Subtitle', required=False)), ('faqs', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('question', wagtail.blocks.TextBlock(help_text='Input Question', required=True)), ('answer', wagtail.blocks.TextBlock(help_text='Input Question', required=True))])))], help_text='Input Frequently Asked Questions'))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HomePageFAQs',
        ),
    ]
