# Generated by Django 5.0.6 on 2024-07-02 05:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_faqs_delete_homepagefaqs'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_section_heading',
            field=models.CharField(blank=True, help_text='Feature Section Title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_section_subheading',
            field=models.CharField(blank=True, help_text='Feature Section Subheading', max_length=255),
        ),
        migrations.CreateModel(
            name='HomePageFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('feature_title', models.CharField(blank=True, max_length=255)),
                ('feature_description', models.TextField(blank=True, max_length=255)),
                ('feature_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
