# Generated by Django 5.0.6 on 2024-07-05 06:48

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_homepage_feature_section_heading_and_more'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='program_section_description',
            field=models.CharField(blank=True, help_text='Feature Section Subheading', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='program_section_heading',
            field=models.CharField(blank=True, help_text='Feature Section Title', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='program_section_subheading',
            field=models.CharField(blank=True, help_text='Feature Section Subheading', max_length=255),
        ),
        migrations.CreateModel(
            name='HomePagePrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('program_title', models.CharField(blank=True, max_length=255)),
                ('program_age', models.CharField(blank=True, max_length=255)),
                ('program_description', models.TextField(blank=True, max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='home.homepage')),
                ('program_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
