# Generated by Django 5.0.6 on 2024-07-13 07:46

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepagelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagelocation',
            name='phone',
            field=wagtail.fields.StreamField([('phone', wagtail.blocks.CharBlock())], blank=True, null=True),
        ),
    ]
