# Generated by Django 5.0.6 on 2024-06-21 07:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_formpage_formfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='image',
        ),
        migrations.AddField(
            model_name='formpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
