# Generated by Django 5.0.6 on 2024-07-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_academicsindexpage_hero_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicsindexpage',
            old_name='hero_features',
            new_name='body',
        ),
    ]
